books/urls.py
from django.urls import path

from . import views

app_name = "books"
urlpatterns = [
    path("search/", views.SearchResultsListView.as_view(), name="search_results"),
    path("<uuid:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("", views.BookListView.as_view(), name="book_list"),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Admin
    path("control/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Local apps
    path("books/", include("books.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        # Debug toolbar
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"
urlpatterns = [
    path("contact/", views.ContactPageView.as_view(), name="contact"),
    path("about/", views.AboutPageView.as_view(), name="about"),
    path("", views.HomePageView.as_view(), name="home"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

books/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to="covers/", blank=True)

    class Meta:
        indexes = [
            models.Index(fields=["id"], name="id_index"),
        ]
        permissions = [
            ("special_status", "Can read all books"),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book_detail", args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    review = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.author} - {self.review}"

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "username")

books/views.py
from django.contrib.auth import mixins
from django.db.models import Q
from django.views import generic

from .models import Book


class BookListView(mixins.LoginRequiredMixin, generic.ListView):
    queryset = Book.objects.order_by("-pk")
    template_name = "books/book_list.html"
    context_object_name = "book_list"
    login_url = "account_login"


class BookDetailView(
    mixins.LoginRequiredMixin, mixins.PermissionRequiredMixin, generic.DetailView
):
    model = Book
    template_name = "books/book_detail.html"
    context_object_name = "book"
    login_url = "account_login"
    permission_required = "books.special_status"
    queryset = Book.objects.all().prefetch_related(
        "reviews__author",
    )


class SearchResultsListView(generic.ListView):
    context_object_name = "book_list"
    template_name = "books/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(
            Q(title__icontains=query) | Q(author__icontains="api")
        )

pages/views.py
from django.views import generic


class HomePageView(generic.TemplateView):
    template_name = "pages/home.html"


class AboutPageView(generic.TemplateView):
    template_name = "pages/about.html"


class ContactPageView(generic.TemplateView):
    template_name = "pages/contact.html"

templates/_base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bookstore{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Favicon -->
     <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <a href="{% url 'pages:home' %}" class="navbar-brand">Bookstore</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:home' %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books:book_list' %}">Books</a>
                    </li>           
                    <li class="nav-item">
                        <a href="{% url 'pages:about' %}" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'pages:contact' %}" class="nav-link">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'account_change_password' %}" class="nav-link">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_logout' %}" class="nav-link">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Register</a>
                        </li>
                    {% endif %}
                </ul>
                <form class="d-flex" action="{% url 'books:search_results' %}" method="get">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" >
                    <button class="btn btn-secondary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <div class="container footer">
        <footer class="py-3">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contact</a></li>
            </ul>
            <p class="text-center text-muted">&copy; 2024 Company, Inc</p>
        </footer>
        </div>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/books/book_detail.html
{% extends "_base.html" %}

{% block title %}{{ book.title }}{% endblock title %}

{% block content %}
    <div class="book-detail">
        {% if book.cover %}
            <img class="bookcover" src="{{ book.cover.url}}" alt="{{ book.title }}">
        {% endif %}
        <h2><a href="">{{ book.title }}</a></h2>
        <p>Author: {{ book.author }}</p>
        <p>Price: {{ book.price }}</p>
        {% if book.reviews.all %}
            <div>
                <h3>Reviews</h3>
                <ul>
                    {% for review in book.reviews.all %}
                        <li>{{ review.review }} &middot; {{ review.author }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/books/book_list.html
{% extends "_base.html" %}

{% block title %}Books{% endblock title %}

{% block content %}
    {% for book in book_list %}
        <div>
            <h2><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock content %}

templates/books/search_results.html
{% extends "_base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}
    <h1>Search Results</h1>

    {% for book in book_list %}
        <div>
            <h3><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h3>
            <p>Author: {{ book.author }}</p>
            <p>Price: $ {{ book.price }}</p>
        </div>
    {% endfor %}
{% endblock content %}

templates/pages/about.html
{% extends "_base.html" %}

{% block title %}About{% endblock title %}

{% block content %}
    <h1>This is our about page.</h1>
{% endblock content %}

templates/pages/contact.html
{% extends "_base.html" %}

{% block title %}Contact{% endblock title %}

{% block content %}
    <h1>This is our contact page.</h1>
{% endblock content %}

templates/pages/home.html
{% extends "_base.html" %}

{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
    <h1>This is our home page.</h1>
    <img class="bookcover" src="{% static 'images/dfp.jpg' %}">
{% endblock content %}